### ISSUE TITLE
[QUESTION/MISC] - Persisting Configuration for Multi-DB setups

### ISSUE THREAD

**Issue by cur1ousdude** [clidey/whodb#268]
It seems the project allows persisting a configuration though a cookie.
But is there also a way to persist configuration trough a file?

Such that on a different host machine I can just use a configuration file + whodb and connect to all my pre-confugured db's without having to re-login to every db individually?

**Comment by modelorona** [comment]
Hi @cur1ousdude apologies for the delay in responding!

We do not currently support using configuration files however you can use Docker environmental variables (https://github.com/clidey/whodb/issues/98) to automatically load in profiles.

https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-env_file-attribute

Here's a link to the docs for more information about using environmental variable profiles: https://whodb.clidey.com/docs/usage-basics/logging-in-to-your-datasources/#login-profiles-environment-variables-setup

Would something like this work for your use case? Would using a configuration file make it easier instead of env profiles?

**Comment by modelorona** [comment]
I'll close this due to inactivity. If you'd like to follow up, please feel free to re-open/comment!

**Comment by daemon-byte** [comment]
Is this still something that can be done? I can't  find any reference to it in the documentation anymore

Update: I figured it out diving in the code: anyone else comes here you add env variables like this

```
      - WHODB_POSTGRES_1={"alias":"Postgres","host":"postgres.internal","user":"username","password":"PASSWORD","database":"postgres", "port":"54320"}
      - WHODB_MYSQL_1={"alias":"Mysql","host":"mysql.internal","user":"username","password":"PASSWORD","database":"mysql"}
```

**Comment by modelorona** [comment]
@daemon-byte ah that's not good that we lost it in the documentation! Thanks for catching that, will fix
