### ISSUE TITLE
How tu run whodb with Ollama as a Docker container?

### ISSUE THREAD

**Issue by saschabrockel** [clidey/whodb#99]
I have Ollama running as a Docker container with the default config and port. whodb does not detect it and there is no option to tell it where it has to look. Is there anything I can do or does it need to be implemented? Of course, I run whodb as a Docker container as well. Both containers run on the same Docker network.

**Comment by hkdeman** [comment]
Helloooo, thank you trying out the ollama integration!

We just rolled out the fix for this issue in the PR: https://github.com/clidey/whodb/pull/101

We have further provided two environment variables to override the host and port below:
- WHODB_OLLAMA_HOST
- WHODB_OLLAMA_PORT

Hope this helps your use case. Do let us know how we can further improve the integration :) We would love feedback.

**Comment by saschabrockel** [comment]
Hey. A thing I would like to have is a version number at least in the info logs at the start and even better somewhere small and tiny on the Web UI. Currently I don't know which version is installed and if it is the latest for example.

**Comment by saschabrockel** [comment]
> Helloooo, thank you trying out the ollama integration!
> 
> We just rolled out the fix for this issue in the PR: #101
> 
> We have further provided two environment variables to override the host and port below:
> 
> * WHODB_OLLAMA_HOST
> * WHODB_OLLAMA_PORT
> 
> Hope this helps your use case. Do let us know how we can further improve the integration :) We would love feedback.

This works with Docker! Used ollama (container name) as host variable and the normal port of the container (11434) as port.

**Comment by hkdeman** [comment]
Glad it works! Would love if there is any feedback you have :) 

Also, will add the version on the UI as a backlog. We will roll it out hopefully soon.
